docproc: fix -Wconversion warnings on 32-bit
On i686, GCC 11.1.1 complains:
```
lib/doc/bin/docproc.c: In function 'find_all_symbols':
lib/doc/bin/docproc.c:433:17: error: conversion to 'ssize_t' {aka 'int'} from 'unsigned int' may change the sign of the result [-Werror=sign-conversion]
  433 |         start = all_list_len;
      |                 ^~~~~~~~~~~~
lib/doc/bin/docproc.c:441:48: error: comparison of integer expressions of different signedness: 'ssize_t' {aka 'int'} and 'unsigned int' [-Werror=sign-compare]
  441 |         for (i = 0; i < (int)data_len && start != all_list_len; i++) {
      |                                                ^~
cc1: all warnings being treated as errors
```

Fix this by declaring all of all_list_len, i, count, and start as
size_t and remove a few casts that are no longer necessary.

Signed-off-by: Ondrej Mosnacek <omosnace@redhat.com>
Signed-off-by: Stephan Mueller <smueller@chronox.de>