internal.h: make inline functions static
With some GCC configurations/build options it is possible for gcc to
ignore the inline hint. As the methods are not declared static, gcc
expects a definition to be provided elsewhere, which is not the case
here resulting in the following linker error:

libtool: link: /home/marcin/br-test-pkg/br-arm-cortex-a9-glibc/host/bin/arm-linux-gcc
-fstack-protector-strong -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE
-D_FILE_OFFSET_BITS=64 -Os -Wl,-z -Wl,relro -Wl,-z -Wl,now -o bin/kcapi
test/bin_kcapi-kcapi-main.o  ./.libs/libkcapi.so -Wl,-rpath
-Wl,/home/marcin/br-test-pkg/br-arm-cortex-a9-glibc/build/libkcapi-0.14.0/.libs
./.libs/libkcapi.so: undefined reference to `_kcapi_common_vmsplice_iov'
./.libs/libkcapi.so: undefined reference to `_kcapi_common_read_data'
./.libs/libkcapi.so: undefined reference to `_kcapi_aio_read_iov'
./.libs/libkcapi.so: undefined reference to `_kcapi_common_recv_data'
./.libs/libkcapi.so: undefined reference to `_kcapi_common_send_data'
./.libs/libkcapi.so: undefined reference to `_kcapi_common_vmsplice_chunk'
./.libs/libkcapi.so: undefined reference to `_kcapi_common_send_meta'
collect2: error: ld returned 1 exit status

$ arm-linux-gcc --version
arm-linux-gcc.br_real (Buildroot 2017.08-git-01078-g95b1dae) 7.1.0

Signed-off-by: Marcin Nowakowski <marcin.nowakowski@imgtec.com>
Signed-off-by: Stephan Mueller <smueller@chronox.de>