apps: Disable -Wstringop-truncation warning on false positives
The GCC v8.1.0 warns:

    In function 'paste',
        inlined from 'get_hmac_file' at apps/kcapi-hasher.c:395:11:
    apps/kcapi-hasher.c:346:2: error: 'strncpy' destination unchanged after copying no bytes [-Werror=stringop-truncation]
      strncpy(dst, src, size);
      ^~~~~~~~~~~~~~~~~~~~~~~

These are false positives because at the end of paste() calls, the buffer is
NULL terminated.

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>
Signed-off-by: Stephan Mueller <smueller@chronox.de>